### ISSUE TITLE
Queue Bug(Error)

### ISSUE THREAD

**Issue by fedesugo** [LegendaryEmoji/Music-Bot#17]
When i play a song, says to me that i need to add more songs to queue, and automaticly bot go out of the vc.
![Captura](https://user-images.githubusercontent.com/66099743/110518422-13e60680-80da-11eb-89f1-38cf58ec6862.PNG)

**Comment by LegendaryEmoji** [comment]
This Happens Some Times, Some Ways To Fix:

- Restart Bot
- Update All NPM Packages (Run This Command In Terminal/Console: **npm update**)

Still Giving Error? Join [Discord Server](https://discord.gg/umMpnqS)

**Comment by LegendaryEmoji** [comment]
Closing This Issue!
